version: 2.1.{build}
os: Visual Studio 2013
platform:
  - Win32
configuration: Release
build:
  project: decompiler.sln
  verbosity: minimal
after_build:
  - 7z a -tzip decompiler-Release.zip .\Release\*
artifacts:
  - path: decompiler-Release.zip
    name: decompiler
